### PR TITLE
Add additional fields

### PR DESCRIPTION
**Pull request by idohalevi**
This PR will allow adding additional fields for every collected log.
@imnotashrimp please review

### CODE REVIEW

**Comment by idohalevi** [comment]
@yakirsudry This should work for you. I tested it on my testing environment, do you mind trying it too before we merge

**Comment by yakirsudry** [comment]
I'll do it during the weekend hopefully

**Comment by yakirsudry** [comment]
I think I managed to set it up correctly. And I added a few prints inside _add_shipping_data that printed correctly. And the logs reached your system. I'm not sure how to verify that the actual fields were added...

**Comment by idohalevi** [comment]
> I think I managed to set it up correctly. And I added a few prints inside _add_shipping_data that printed correctly. And the logs reached your system. I'm not sure how to verify that the actual fields were added...

In the README file, you can see explanations on how to add the environment fields. Try to add the ones you wanted, ship it to Logz.io, and check in Kibana if the logs have those you added

**Comment by yakirsudry** [comment]
Seems perfect (the 3rd field is some environment variable)
image

I looked at the code. I think there is a bug on lines 71, 74 that you modify the dict while traversing it, which is bad. From the documentation:

Iterating views while adding or deleting entries in the dictionary may raise a RuntimeError or fail to iterate over all entries.

**Pull request merged**
